[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pygration"
version = "0.0.2"

[project.scripts]
pygration = "pygration_cli:main"

[tool.setuptools]
py-modules = ["pygration_cli"]
packages = ["pygration"]

[tool.isort]
profile = "black"
